"""
Django settings for meteor project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)_@^*)a^&dn(=0eq*&)h=fj+gjjv=hos^44hl^v5s-*7+3=ifs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['meteordub.uz', 'www.meteordub.uz', '127.0.0.1', '176.96.243.178']



# Application definition

INSTALLED_APPS = [
    "unfold", 
    "unfold.contrib.filters", 
    "unfold.contrib.forms", 
    "unfold.contrib.inlines", 
    "unfold.contrib.import_export", 
    "unfold.contrib.guardian",  
    "unfold.contrib.simple_history", 
    "unfold.contrib.location_field", 
    "unfold.contrib.constance",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'user_side.apps.UserSideConfig',
    'rest_framework_simplejwt.token_blacklist',
    'docs',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meteor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meteor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [BASE_DIR / 'user_side' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15, 
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'user_side.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_ROOT = BASE_DIR / 'staticfiles'
BASE_DIR / "admin"

STATIC_URL = '/static/'

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


MEDIA_ROOT = BASE_DIR / 'media'

# UNFOLD ADMIN CONFIGURATION
UNFOLD = {
    "SITE_TITLE": "Meteor Admin",
    "SITE_HEADER": "Meteor Administration",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "DASHBOARD_CALLBACK": "meteor.settings.dashboard_callback",
    "TEMPLATES": {
        "DASHBOARD": "admin/index.html",  
    },
    "ENVIRONMENT": "meteor.settings.environment_callback",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Dashboard"),
                "separator": True,
                "items": [
                    {
                        "title": _("Overview"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Content"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Anime"),
                        "icon": "movie",
                        "link": reverse_lazy("admin:user_side_anime_changelist"),
                    },
                    {
                        "title": _("Episodes"),
                        "icon": "video_library",
                        "link": reverse_lazy("admin:user_side_episode_changelist"),
                    },
                    {
                        "title": _("Genres"),
                        "icon": "category",
                        "link": reverse_lazy("admin:user_side_genre_changelist"),
                    },
                ],
            },
            {
                "title": _("Users & Payments"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:user_side_user_changelist"),
                    },
                    {
                        "title": _("Subscriptions"),
                        "icon": "card_membership",
                        "link": reverse_lazy("admin:user_side_subscription_changelist"),
                    },
                    {
                        "title": _("Payments"),
                        "icon": "payment",
                        "link": reverse_lazy("admin:user_side_payment_changelist"),
                    },
                ],
            },
        ],
    },
}
def dashboard_callback(request, context):
    from user_side.models import User, Anime, Episode, AnonymousSession
    from django.db.models import Sum, Count
    from django.utils import timezone
    from datetime import timedelta
    import json
    
    total_users = User.objects.count()
    premium_users = User.objects.filter(is_premium=True).count()
    total_anime = Anime.objects.filter(is_published=True).count()
    total_episodes = Episode.objects.filter(is_published=True).count()
    total_guests = AnonymousSession.objects.count()
    active_guests = AnonymousSession.objects.filter(last_seen_at__gte=timezone.now() - timedelta(days=1)).count()
    
    last_week = timezone.now() - timedelta(days=7)
    new_users_week = User.objects.filter(created_at__gte=last_week).count()
    
    # User growth (30 days)
    user_growth_labels = []
    user_growth_data = []
    premium_growth_data = []
    
    for i in range(30, -1, -1):
        date = timezone.now() - timedelta(days=i)
        user_growth_labels.append(date.strftime('%m/%d'))
        user_growth_data.append(User.objects.filter(created_at__date__lte=date.date()).count())
        premium_growth_data.append(User.objects.filter(created_at__date__lte=date.date(), is_premium=True).count())
    
    # Top anime
    top_anime = Anime.objects.filter(is_published=True).order_by('-views_count')[:5]
    top_anime_labels = [anime.title[:25] for anime in top_anime]
    top_anime_data = [anime.views_count for anime in top_anime]
    
    # Guest activity (7 days)
    guest_labels = []
    guest_data = []
    
    for i in range(7, -1, -1):
        date = timezone.now() - timedelta(days=i)
        guest_labels.append(date.strftime('%m/%d'))
        guest_data.append(AnonymousSession.objects.filter(first_seen_at__date=date.date()).count())
    
    recent_episodes = Episode.objects.select_related('anime').filter(is_published=True).order_by('-created_at')[:5]
    
    context.update({
        "kpi": [
            {"title": "Total Users", "metric": f"{total_users:,}", "footer": f"+{new_users_week} this week", "icon": "👥"},
            {"title": "Premium Users", "metric": f"{premium_users:,}", "footer": f"{(premium_users/total_users*100):.1f}%" if total_users > 0 else "0%", "icon": "⭐"},
            {"title": "Total Anime", "metric": f"{total_anime:,}", "footer": f"{total_episodes:,} episodes", "icon": "🎬"},
            {"title": "Guest Sessions", "metric": f"{total_guests:,}", "footer": f"{active_guests} active today", "icon": "🌐"},
        ],
        "user_growth_labels": json.dumps(user_growth_labels),
        "user_growth_data": json.dumps(user_growth_data),
        "premium_growth_data": json.dumps(premium_growth_data),
        "top_anime_labels": json.dumps(top_anime_labels),
        "top_anime_data": json.dumps(top_anime_data),
        "guest_labels": json.dumps(guest_labels),
        "guest_data": json.dumps(guest_data),
        "recent_episodes": recent_episodes,
    })
    return context

def environment_callback(request):
    return ["Development", "success"]


