# Generated by Django 5.2.7 on 2025-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
