# Generated by Django 5.2.7 on 2025-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_alter_user_premium_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
