# Generated by Django 5.2.7 on 2025-10-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0005_remove_genre_genre_slug_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='user_side.genre'),
        ),
    ]
