# Generated by Django 5.2.7 on 2025-10-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_anime_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeGenre',
        ),
    ]
