# Generated by Django 5.2.7 on 2025-10-20 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_delete_animegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeview',
            name='anonymous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.anonymoussession'),
        ),
        migrations.AlterField(
            model_name='animeview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
