# Generated by Django 5.2.7 on 2025-10-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0009_alter_watchhistory_anonymous_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeview',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='animeview',
            name='anonymous_session',
        ),
        migrations.RemoveField(
            model_name='animeview',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='animeview',
            name='user',
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='country',
            field=models.CharField(default='UZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='device_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='watch_duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', 'anime', 'episode'], name='user_side_w_user_id_2054f8_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['anonymous_session', 'anime', 'episode'], name='user_side_w_anonymo_33a6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['anime', 'watched_at'], name='user_side_w_anime_i_e47046_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['episode', 'watched_at'], name='user_side_w_episode_3fa7f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anonymous_session__isnull', True), ('user__isnull', False)), models.Q(('anonymous_session__isnull', False), ('user__isnull', True)), _connector='OR'), name='watch_history_user_or_session'),
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'anime', 'episode'), name='unique_user_anime_episode'),
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_session__isnull', False)), fields=('anonymous_session', 'anime', 'episode'), name='unique_session_anime_episode'),
        ),
        migrations.DeleteModel(
            name='AnimeView',
        ),
    ]
