# Generated by Django 5.2.7 on 2025-10-21 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0010_remove_animeview_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='episode',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user_side.episode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='anonymous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.anonymoussession'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
