# Generated by Django 5.2.7 on 2025-10-21 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0011_like_episode_alter_like_anonymous_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.episode'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user_side.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.anime'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.anime'),
        ),
        migrations.AlterField(
            model_name='like',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.episode'),
        ),
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['anime', 'is_approved', '-created_at'], name='user_side_c_anime_i_9ce379_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['episode', 'is_approved', '-created_at'], name='user_side_c_episode_227764_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', '-created_at'], name='user_side_c_parent__75a591_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['anime', 'is_like'], name='user_side_l_anime_i_003154_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['episode', 'is_like'], name='user_side_l_episode_73de15_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('anime__isnull', False), ('episode__isnull', True), ('user__isnull', False)), fields=('user', 'anime'), name='unique_user_anime_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('episode__isnull', False), ('user__isnull', False)), fields=('user', 'episode'), name='unique_user_episode_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('anime__isnull', False), ('anonymous_session__isnull', False), ('episode__isnull', True)), fields=('anonymous_session', 'anime'), name='unique_anon_anime_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_session__isnull', False), ('episode__isnull', False)), fields=('anonymous_session', 'episode'), name='unique_anon_episode_like'),
        ),
    ]
