# Generated by Django 5.2.7 on 2025-10-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0012_alter_comment_options_remove_comment_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='total_likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
