# Generated by Django 5.2.7 on 2025-10-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0013_episode_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='total_comments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
