# Generated by Django 5.2.7 on 2025-10-21 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0014_anime_total_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='user_side.anime')),
                ('anonymous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.anonymoussession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'anime'], name='user_side_f_user_id_ce12b7_idx'), models.Index(fields=['anonymous_session', 'anime'], name='user_side_f_anonymo_2a8170_idx'), models.Index(fields=['anime', 'added_at'], name='user_side_f_anime_i_443cc8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('anonymous_session__isnull', True), ('user__isnull', False)), models.Q(('anonymous_session__isnull', False), ('user__isnull', True)), _connector='OR'), name='favorite_user_or_session'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'anime'), name='unique_user_anime_favorite'), models.UniqueConstraint(condition=models.Q(('anonymous_session__isnull', False)), fields=('anonymous_session', 'anime'), name='unique_session_anime_favorite')],
            },
        ),
    ]
