# Generated by Django 5.2.7 on 2025-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='total_favorites',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
